name: nzz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_screenutil: ^5.3.0
  flutter_swiper: ^1.1.6
  flutter_staggered_grid_view: ^0.6.1
  dio: ^4.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/appbar_search_icon.png
    - images/back_icon_light.png
    - images/back_icon_dark.png
    - images/focus_icon.png
    - images/quality_icon.png
    - images/money_icon.png
    - images/index_cate_food.png
    - images/index_cate_quality.png
    - images/index_cate_make.png
    - images/index_cate_vouchers.png
    - images/location_icon.png
    - images/hui_icon.png
    - images/quan_icon.png
    - images/xkzx_icon.png
    - images/star_light.png
    - images/star_dark.png
    - images/cate_scroll_icon.png
    - images/cate_toogle_close.png
    - images/jpg_tag.png
    - images/ksz_tag.png
    - images/empty_icon.png
    - images/sort_default.png
    - images/sort_up.png
    - images/sort_down.png
    
    

